  
name: ewastools
owner: iuc
description: Infinium Human Methylation BeadChip Analysis 
homepage_url: https://bioconductor.org/packages/release/bioc/html/minfi.html
remote_repository_url: https://github.com/kpbioteam/ewas_galaxy 
categories:
  - Epigenetics 
